// Orchestrates one account's "Claude Weekly Intelligence" run: gather this
// week's analytics -> send to Claude -> validate -> store -> serve.
const fs = require('fs');
const path = require('path');
const { DATA_DIR, ACCOUNTS, todayStr } = require('./graph');
const { buildAccountWeeklyPayload } = require('./weeklyMetrics');
const { generateWeeklyAnalysis, CLAUDE_MODEL } = require('./claudeClient');

const STORE_ROOT = path.join(DATA_DIR, 'weekly-analysis');

function accountDir(accountId) {
  const dir = path.join(STORE_ROOT, accountId);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function findAccount(accountId) {
  return ACCOUNTS.find((a) => a.id === accountId);
}

function listRecordFiles(accountId) {
  const dir = accountDir(accountId);
  return fs.readdirSync(dir).filter((f) => /^\d{4}-\d{2}-\d{2}\.json$/.test(f)).sort();
}

function readRecord(accountId, dateStr) {
  const file = path.join(accountDir(accountId), `${dateStr}.json`);
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return null; }
}

function getLatestAnalysis(accountId) {
  const files = listRecordFiles(accountId);
  if (!files.length) return null;
  return readRecord(accountId, files[files.length - 1].replace('.json', ''));
}

function listAnalyses(accountId, limit = 12) {
  const files = listRecordFiles(accountId).slice(-limit).reverse();
  return files.map((f) => readRecord(accountId, f.replace('.json', ''))).filter(Boolean);
}

// One record per account per calendar day it was (re)generated. Regenerating
// on the same day overwrites that day's file rather than piling up duplicates.
async function runWeeklyAnalysis(accountId, { force = false } = {}) {
  const acc = findAccount(accountId);
  if (!acc) throw new Error(`Unknown account "${accountId}"`);

  const key = todayStr();
  if (!force) {
    const existing = readRecord(accountId, key);
    if (existing) return existing;
  }

  const dataSnapshot = await buildAccountWeeklyPayload(acc);
  const { analysis, model } = await generateWeeklyAnalysis(dataSnapshot);

  const record = {
    account_id: acc.id,
    account_name: acc.name,
    generated_at: new Date().toISOString(),
    period_label: `${dataSnapshot.period.current_7d.since} to ${dataSnapshot.period.current_7d.until}`,
    period: dataSnapshot.period,
    model: model || CLAUDE_MODEL,
    data_snapshot: dataSnapshot,
    analysis,
  };

  fs.writeFileSync(path.join(accountDir(accountId), `${key}.json`), JSON.stringify(record, null, 2));
  return record;
}

async function runWeeklyAnalysisForAllAccounts({ force = false } = {}) {
  const results = [];
  for (const acc of ACCOUNTS) {
    try {
      results.push({ account_id: acc.id, ok: true, record: await runWeeklyAnalysis(acc.id, { force }) });
    } catch (e) {
      results.push({ account_id: acc.id, ok: false, error: e.message });
    }
  }
  return results;
}

function generateReportText(record) {
  if (!record) return 'No analysis available yet.';
  const a = record.analysis;
  const lines = [];
  lines.push(`CLAUDE WEEKLY INTELLIGENCE — ${record.account_name}`);
  lines.push(`Period: ${record.period_label}`);
  lines.push(`Generated: ${record.generated_at}`);
  lines.push('AI analysis generated by Claude using your account\'s analytics data.');
  lines.push('');
  lines.push('EXECUTIVE SUMMARY');
  lines.push(a.executive_summary || '(none)');
  lines.push('');
  lines.push('IMPROVED');
  (a.improvements || []).forEach((i) => lines.push(`+ ${i.metric}${i.change_pct != null ? ` (${i.change_pct}%)` : ''} — ${i.detail}`));
  lines.push('');
  lines.push('DECLINED');
  (a.declines || []).forEach((d) => lines.push(`- ${d.metric}${d.change_pct != null ? ` (${d.change_pct}%)` : ''} — ${d.detail}`));
  lines.push('');
  lines.push('TOP CONTENT');
  (a.top_posts || []).forEach((p) => lines.push(`* [${p.platform}] ${p.caption_or_title} — ${p.why_it_stands_out} ${p.url ? `(${p.url})` : ''}`));
  lines.push('');
  lines.push('CONTENT PATTERNS');
  (a.content_patterns || []).forEach((s) => lines.push(`- ${s}`));
  lines.push('');
  lines.push('ENGAGEMENT ANALYSIS');
  (a.engagement_analysis || []).forEach((s) => lines.push(`- ${s}`));
  lines.push('');
  lines.push('PLATFORM COMPARISON');
  (a.platform_comparison || []).forEach((p) => lines.push(`- ${p.platform}: reach ${p.reach ?? '–'}, engagement ${p.engagement ?? '–'}, rate ${p.engagement_rate ?? '–'}%, posts ${p.content_volume ?? '–'}${p.note ? ` (${p.note})` : ''}`));
  lines.push('');
  lines.push('POSTING CONSISTENCY');
  lines.push(JSON.stringify(a.posting_consistency || {}, null, 2));
  lines.push('');
  lines.push('RECOMMENDATIONS');
  (a.recommendations || []).forEach((r) => lines.push(`- ${r}`));
  lines.push('');
  lines.push('NEXT WEEK CONTENT PLAN');
  (a.next_week_plan || []).forEach((p) => lines.push(`${p.day} — ${p.platform} — ${p.format}: ${p.topic}${p.hook ? ` (hook: ${p.hook})` : ''} — ${p.reason}`));
  lines.push('');
  lines.push('DATA LIMITATIONS');
  (a.data_limitations || []).forEach((s) => lines.push(`- ${s}`));
  return lines.join('\n');
}

module.exports = {
  runWeeklyAnalysis,
  runWeeklyAnalysisForAllAccounts,
  getLatestAnalysis,
  listAnalyses,
  generateReportText,
  findAccount,
};
